name: micro_app_login
description: A new Flutter package project.
version: 1.0.4
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  micro_core:
    git:
      url: https://github.com/oliveira-gabriel/micro_core.git
      ref: 1.0.1

  micro_commons_design_system:
    git:
      url: https://github.com/oliveira-gabriel/micro_commons_design_system.git
      ref: 1.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
